package com.lmax.disruptor.jmh_generated;
public class MultiProducerSequencerBenchmark_StateMultiProducerSequencerUnsafe_jmhType extends MultiProducerSequencerBenchmark_StateMultiProducerSequencerUnsafe_jmhType_B3 {
}

